### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by kirbyfan64** [google/anvil-build#15]
There hasn't been a commit in three years... :(

**Comment by benvanik** [comment]
Yep - you'll want to check out bazel - this was built because bazel was still 3-4 years away from public release and I needed something in the interim. Bazel is much better supported, works on all platforms, and has great documentation - I recommend taking a peek!

**Comment by kirbyfan64** [comment]
True, but it also depends on the JVM and doesn't have any JS rules (yet?). :(

FWIW maybe you should make it explicit somewhere, maybe in the description?

**Comment by benvanik** [comment]
The closure rules are a superset of the ones in this repo:
https://github.com/bazelbuild/rules_closure

(they have css, soy, and closure compiler)

Will do!
